import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    ContainerPrincipal:{
        flex:1,
        backgroundColor:'#1a1a1a', 
        // alignItems: 'center',
    },
    ContenedorHijoBtns:{
        width:400,
        height:50,
        backgroundColor: '#2c2c2c',
        borderRadius:15,
        marginTop:10,
        justifyContent: 'center',
        alignItems:'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    ContenedorHijo: {
        width:400,
        height:400,
        backgroundColor: '#ffffff',
        borderRadius:15,
        marginTop: 10,
        position: 'relative',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4.65,
        elevation: 8,
    },
    LogoReservaAgenda:{
        width: 60,
        height: 60,
        borderRadius: 30,
        borderWidth: 3,
        borderColor: '#d4a574',
    },
    TextoPerfil: {
        position: 'absolute',
        top: 185,
        left: 65,
        fontSize: 20,
        color: '#2c2c2c',
        fontWeight: 'bold',
    },
    ViewImagen: {
        width: 400,
        height: 140, // Reducir altura para dar más espacio a la info
        marginTop: -15, // Overlap sutil con el header
    },
    ViewDetalles: {
        position: 'absolute',
        top: 200, // Ajustar posición
        left: 15,
        right: 15,
    },
    ViewBtnCita: {
        backgroundColor: '#d4a574',
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 20,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    ViewPrincipalModalGaleria: {
        flex:1,
        backgroundColor: '#f8f9fa',
        justifyContent: 'flex-start',
        alignItems: 'center',
        paddingTop: 40, 
    },
    ViewTituloCorte: {
        backgroundColor:'#ffffff',
        marginTop: 20,
        borderRadius: 15,
        paddingHorizontal: 20,
        paddingVertical: 15,
        width: '100%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 3,
    },
    Galeria:{
        marginTop: 15,
        backgroundColor: '#f8f9fa',
        borderRadius: 12,
        padding: 8,
        borderWidth: 1,
        borderColor: '#e9ecef',
    },
    SeparadorSeccion: {
        height: 1,
        backgroundColor: '#e9ecef',
        marginVertical: 25,
        marginHorizontal: 20,
        borderRadius: 1,
    },
    // Nuevo estilo para botón cerrar
    BotonCerrarModal: {
        position: 'absolute',
        top: 45,
        right: 20,
        backgroundColor: '#ffffff',
        borderRadius: 20,
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 3.84,
        elevation: 5,
    },
    HeaderBarbero: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 15,
        backgroundColor: '#ffffff',
        borderTopLeftRadius: 15,
        borderTopRightRadius: 15,
    },
    InfoBarbero: {
        marginLeft: 15,
        flex: 1,
    },
    NombreBarbero: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#2c2c2c',
        marginBottom: 4,
    },
    RatingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 4,
    },
    RatingStars: {
        fontSize: 14,
        marginRight: 5,
    },
    RatingText: {
        fontSize: 14,
        color: '#666',
        fontWeight: '600',
    },
    EspecialidadText: {
        fontSize: 12,
        color: '#d4a574',
        fontStyle: 'italic',
    },
    ServiciosContainer: {
        backgroundColor: '#f8f9fa',
        padding: 12,
        borderRadius: 10,
        marginBottom: 15,
    },
    InfoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 6,
    },
    InfoLabel: {
        fontSize: 14,
        color: '#666',
        fontWeight: '500',
    },
    InfoValue: {
        fontSize: 14,
        color: '#2c2c2c',
        fontWeight: 'bold',
    },
    BtnCitaText: {
        color: '#ffffff',
        fontWeight: 'bold',
        fontSize: 16,
    },

})

export default styles