import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    ViewPrincipalModalGaleria: {
        flex:1,
        backgroundColor: '#f8f9fa',
        justifyContent: 'flex-start',
        alignItems: 'center',
        paddingTop: 40, 
    },
        BotonCerrarModal: {
        position: 'absolute',
        top: 45,
        right: 20,
        backgroundColor: '#ffffff',
        borderRadius: 20,
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 3.84,
        elevation: 5,
    },
        ViewTituloCorte: {
        backgroundColor:'#ffffff',
        marginTop: 20,
        borderRadius: 15,
        paddingHorizontal: 20,
        paddingVertical: 15,
        width: '100%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 3,
    },
        Galeria:{
        marginTop: 15,
        backgroundColor: '#f8f9fa',
        borderRadius: 12,
        padding: 8,
        borderWidth: 1,
        borderColor: '#e9ecef',
    },
        SeparadorSeccion: {
        height: 1,
        backgroundColor: '#e9ecef',
        marginVertical: 25,
        marginHorizontal: 20,
        borderRadius: 1,
    },
})